import type { SpriteData } from './customers';

const iconUndo: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '................',
    '.....TTTT.......',
    '....TTTTTT......',
    '...TTTTTTTT.....',
    '..TTT....TTT....',
    '..TT......TTT...',
    '.........TTTT...',
    '..........TTT...',
    '..........TTT...',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};

const iconServe: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '................',
    '..GGGGGGGGGG....',
    '..G........G....',
    '..GGGGGGGGGG.ss.',
    '.......GG...ss..',
    '......GGGG..ss..',
    '.....GGGGGG.ss..',
    '....GGGGGGG.s...',
    '....GGGGGG......',
    '....GGGGGG......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};

const iconBook: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '..BBBBBBBBB.....',
    '..BCCCCCCCCB....',
    '..BCCCCCCCCB....',
    '..BCCCCCCCCB....',
    '..BCCCCCCCCB....',
    '..BCCCCCCCCB....',
    '..BCCCCCCCCB....',
    '..BCCCCCCCCB....',
    '..BCCCCCCCCB....',
    '..BBBBBBBBB.....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};

const iconSettings: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '.....ssss.......',
    '....ssssss......',
    '...ss.EE.ss.....',
    '..ss.EEEE.ss....',
    '..ssEEEEEEss....',
    '..ssEEEEEEss....',
    '..ss.EEEE.ss....',
    '...ss.EE.ss.....',
    '....ssssss......',
    '.....ssss.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};

const iconStar: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '.......YY.......',
    '.......YY.......',
    '......YYYY......',
    'YYYYYYYYYYYYYYYY',
    '.YYYYYYYYYYYYYY.',
    '..YYYYYYYYYYYY..',
    '...YYYYYYYYYY...',
    '....YYYYYYYY....',
    '....YYYYYYYY....',
    '...YYYY..YYYY...',
    '..YYYY....YYYY..',
    '..YYY......YYY..',
    '................',
    '................',
    '................',
  ],
};

const stationEspresso: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '..ssssssssss....',
    '..SSSSSSSSSS....',
    '..SSSSSSSSSS....',
    '..ssssssssss....',
    '.......ss.......',
    '.......ss.......',
    '.....KKKKKK.....',
    '.....KKKKKK.....',
    '.....KKKKKK.....',
    '................',
    '...bbbbbbbbb....',
    '...BBBBBBBBB....',
    '................',
    '................',
    '................',
  ],
};

const stationMilk: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '..ss............',
    '..ss............',
    '..WWWWW.........',
    '..WWWWWs........',
    '..WWWWWs........',
    '..WWWWWs........',
    '..WWWWW.........',
    '..WWWWW.........',
    '...WWWW.........',
    '................',
    '....GGG.........',
    '...GGGGG........',
    '................',
    '................',
    '................',
  ],
};

const stationAssembly: SpriteData = {
  w: 16, h: 16,
  rows: [
    '................',
    '................',
    '...WWWWWWWW.....',
    '..KKKKKKKKKK....',
    '..WWWWWWWWWW.ss.',
    '..WWWWWWWWWW.ss.',
    '..WWWWWWWWWW.ss.',
    '..WWWWWWWWWW.s..',
    '...WWWWWWWW.....',
    '....WWWWWW......',
    '................',
    '...CCCCCCCC.....',
    '..CCCCCCCCCC....',
    '................',
    '................',
    '................',
  ],
};

/** Pixel-art app icon: takeaway cup on a coffee-brown roundel. */
export const APP_ICON: SpriteData = {
  w: 32, h: 32,
  rows: [
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KKBBBBBBBBBBBBBBBBBBBBBBBBBBBBKK',
    'KKBBBBBBBBBBBBBBBBBBBBBBBBBBBBKK',
    'KKBBBBBBBBBBBBBBBBBBBBBBBBBBBBKK',
    'KKBBBBBBBBBBssssssBBBBBBBBBBBBKK',
    'KKBBBBBBBBBssssssssBBBBBBBBBBBKK',
    'KKBBBBBBBBBLLLLLLLLBBBBBBBBBBBKK',
    'KKBBBBBBBCCssssssssCCBBBBBBBBBKK',
    'KKBBBBBBCCCCCCCCCCCCCCBBBBBBBBKK',
    'KKBBBBBBCCCCCCCCCCCCCCBBBBBBBBKK',
    'KKBBBBBBCWWWWWWWWWWWWCBBBBBBBBKK',
    'KKBBBBBBCWWWWWWWWWWWWCBBBBBBBBKK',
    'KKBBBBBBCWWWWWWWWWWWWCBBBBBBBBKK',
    'KKBBBBBBCWWWWWWWWWWWWCBBBBBBBBKK',
    'KKBBBBBBCWWWWWWWWWWWWCBBBBBBBBKK',
    'KKBBBBBBCBBBBBBBBBBWWCBBBBBBBBKK',
    'KKBBBBBBCBBBBBBBBBBWWCBBBBBBBBKK',
    'KKBBBBBBCBBBBBBBBBBWWCBBBBBBBBKK',
    'KKBBBBBBCBBBBBBBBBBWWCBBBBBBBBKK',
    'KKBBBBBBCBBBBBBBBBBWWCBBBBBBBBKK',
    'KKBBBBBBCBBBBBBBBBBWWCBBBBBBBBKK',
    'KKBBBBBBCCCCCCCCCCCCCCBBBBBBBBKK',
    'KKBBBBBBBCCCCCCCCCCCCBBBBBBBBBKK',
    'KKBBBBBBBBCCCCCCCCCCBBBBBBBBBBKK',
    'KKBBBBBBBBBBCCCCCCBBBBBBBBBBBBKK',
    'KKBBBBBBBBBBBBBBBBBBBBBBBBBBBBKK',
    'KKBBBBBBBBBBBBBBBBBBBBBBBBBBBBKK',
    'KKBBBBBBBBBBBBBBBBBBBBBBBBBBBBKK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  ],
};

export const UI_SPRITES: Record<string, SpriteData> = {
  'icon-undo': iconUndo,
  'icon-serve': iconServe,
  'icon-book': iconBook,
  'icon-settings': iconSettings,
  'icon-star': iconStar,
  'station-espresso': stationEspresso,
  'station-milk': stationMilk,
  'station-assembly': stationAssembly,
};
